### ISSUE TITLE
Allow droplet ID retrieval

### ISSUE THREAD

**Issue by yberreby** [kbknapp/doapi-rs#18]
I am trying to create a droplet, and retrieve its ID.

``` rust
manager.droplets().create(&settings).retrieve().unwrap()
```

This returns a [`doapi::response::Droplet`](http://kbknapp.github.io/doapi-rs/docs/doapi/response/struct.Droplet.html), which [contains the droplet ID](http://kbknapp.github.io/doapi-rs/docs/src/doapi/response/droplet.rs.html#27).
Unfortunately, **this struct's fields are all private**, and it exposes no way to access the ID, nor any other field. Would you consider making these fields public, or adding accessors for them?

As a side note, why are all numeric fields (`id`, `memory`, `vcpus`) of type `f64`? I suspect fractional CPUs and IDs are a rarity :)

**Comment by kbknapp** [comment]
This should be an easy change. Unfortunately I don't have huge amount of time to work on `doapi` or `docli` right now, although it is on my list of things to knock out. I've seen you've posted a few PRs and issues, if you're interested I can add you as a collaborator on this repo giving you push access?

For the `f64` note, at the time of creation I wasn't sure if those numbers would ever return a decimal from DO, so I made them f64 to be safe (because a JSON number can be either whole or decimal). They could safely be changed to `u64` though.

**Comment by yberreby** [comment]
> Unfortunately I don't have huge amount of time to work on doapi or docli right now, although it is on my list of things to knock out. I've seen you've posted a few PRs and issues, if you're interested I can add you as a collaborator on this repo giving you push access?

@kbknapp I don't have much free time either, unfortunately, because my studies are taking up my time.
I'm working on a DigitalOcean-related project when I can, though, hence the PRs and issues I posted.
I _may_ land a fix every once in a while, so if you want to, feel free to add me, but I can't promise anything.

**Comment by kbknapp** [comment]
No worries, I'll add you. There's no pressure, this is spare time project for me too. So whichever of us knocks it out is fine :smile:

**Comment by yberreby** [comment]
Closed by #19.
